name: AlternateSpider
on:
  push:
  #schedule:
  #  - cron: 30 * * * sun
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Nokogiri
        run: gem install nokogiri --no-document
  spider:
      - uses: actions/checkout@main
      - name: Check Alternate
        run: ruby alternate_spider.rb {{ secrets.PROWL_API_KEY }}
