name: AlternateSpider
on:
  schedule:
    - cron: 30 10,16 * * mon-fri
jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Nokogiri
        run: gem install nokogiri --no-document
      - name: Check Alternate
        run: ruby alternate_spider.rb ${{ secrets.PROWL_API_KEY }}
