name: AlternateSpider
on:
  push:
  #schedule:
  #  - cron: 30 * * * sun
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: gem install nokogiri --no-document
      - run: ruby alternate_spider.rb '{{ secrets.PROWL_API_KEY }}'
